### PR TITLE
Get error count from recent redumper log

### PR DESCRIPTION
**Pull request by fuzz6001**
I have simplified the process so it may not work correctly in the situation the original code envisioned.
It also does not process previous logs.

# Previous log
```
data errors [dump.bin]:
  ECC: 10
  EDC: 10
  redump: 10
```

# Recent log
```
*** MODE: info
CD-ROM [dump.bin]:
  sectors count: 271236
  mode1 sectors: 271236
  ECC errors: 65
  EDC errors: 65

  REDUMP.ORG errors: 65
```

### CODE REVIEW

**Comment by mnadareski** [comment]
@fuzz6001 is this for the version that's currently bundled with MPF? Or is it a version that I haven't updated to yet?

**Comment by mnadareski** [comment]
Also, as much as it may pain you to do so, I'd strongly encourage keeping to the existing code format. I have my reasons. It seems like it's as easy as updating the "seek to" and "redump" lines.

**Comment by fuzz6001** [comment]
@mnadareski 
> is this for the version that's currently bundled with MPF? Or is it a version that I haven't updated to yet?

This is for the currently bundled version. (from build 92)
https://github.com/superg/redumper/commit/8856281ac93096fb45d37a9c6bb9a8a026985020

I will not be able to work on this PR until the weekend, so this PR should be closed.

**Comment by mnadareski** [comment]
Not worth closing a PR just because it can't be worked on. I'll leave it open, new MPF is planned for later this week.

**Comment by fuzz6001** [comment]
I reverted and changed it back.
This is just a string replacement.

**Comment by mnadareski** [comment]
This still isn't a flat replacement. I'll just make any cosmetic changes later.

**Pull request merged**
